data_sources:
  lw_dp:
    version: ??
    url: http://localhost:8082/
    chunk_length: 65536
    ds_impl:
      lib: th2-data-services-lwdp
      version: 3.1.0.1
    cli_ds_class: Lwdp3HttpDataSource

  rpt_dp:
    version: ??
    url: http://localhost:8080/
    chunk_length: 65536
    ds_impl:
      lib: th2-data-services-rdp
      version: 0.0.0.1.dev11486288321
    cli_ds_class: Rpt5HttpDataSource
